In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [3]:
arr.shape

(5,)

In [4]:
arr.ndim

1

In [5]:
arr.dtype

dtype('int64')

In [6]:
arr.size, arr.itemsize, arr.nbytes

(5, 8, 40)

In [7]:
anp = np.arange(0, 10, 3)
print(anp)

lspace = np.linspace(0, 10, 5)
print(lspace)

[0 3 6 9]
[ 0.   2.5  5.   7.5 10. ]


In [8]:
rarr = np.random.randn(3, 4)
print(rarr)

[[ 1.33414769 -1.16838639 -0.38936533 -0.76116965]
 [ 0.14374333  0.18241705 -1.45992277 -0.32111434]
 [ 0.32909039  1.48577412  0.54747527 -0.15633466]]


In [9]:
z = np.full_like(rarr, 7)
print(z)

[[7. 7. 7. 7.]
 [7. 7. 7. 7.]
 [7. 7. 7. 7.]]


In [10]:
r = np.array([[1, 2], [3, 4]])
a = np.repeat(r, 2, axis=1)
print(a)

[[1 1 2 2]
 [3 3 4 4]]


In [11]:
# use of np.diag(v)
v = np.array([1, 2, 3])
d = np.diag(v)
print(d)

# Extracting the diagonal
print(d.diagonal())         

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[1 2 3]


In [12]:
# How to create a n*m matrix of 1 to n*m
n, m = 5, 12
a = np.arange(1, n * m + 1).reshape(n, m)
print(a)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32 33 34 35 36]
 [37 38 39 40 41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56 57 58 59 60]]


In [13]:
print(a[1, 5])
print(a[1, :])
print(a[0, 1:12:2])

mask = a < 10
filtered_a = a[mask]
print(filtered_a)

18
[13 14 15 16 17 18 19 20 21 22 23 24]
[ 2  4  6  8 10 12]
[1 2 3 4 5 6 7 8 9]


In [14]:
print(np.any(a < 29, axis=1))

[ True  True  True False False]


In [15]:
rows = [1, 2]
cols = [5, 6]
print(a[rows, cols])

[18 31]


In [16]:
np.where(a < 29, 'Yes', 'No')

array([['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
        'Yes', 'Yes', 'Yes'],
       ['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
        'Yes', 'Yes', 'Yes'],
       ['Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No',
        'No', 'No'],
       ['No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
        'No'],
       ['No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
        'No']], dtype='<U3')

In [17]:
na = a.reshape((12, -1))

In [18]:
na

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60]])

In [19]:
flat = na.flatten()

In [20]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [21]:
left, right = np.split(flat, 2)
print(left)

print(right)

p1, p2, p3, p4 = np.split(flat, [10, 20, 25], axis=0)

print(p1, "-", p2, "-", p3, "-", p4)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
[31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54
 55 56 57 58 59 60]
[ 1  2  3  4  5  6  7  8  9 10] - [11 12 13 14 15 16 17 18 19 20] - [21 22 23 24 25] - [26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60]


In [22]:

arr = np.arange(20)
print(arr)

np.random.shuffle(arr)
print(arr)

argsort = np.argsort(arr)
print(argsort)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[14 10 16 12  3  1 17 11 19  8  6 18  0  4  2 13 15  5  7  9]
[12  5 14  4 13 17 10 18  9 19  1  7  3 15  0 16  2  6 11  8]


In [23]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [24]:
np.prod(a, axis=1)


array([           479001600,     1295295050649600,   599555620984320000,
       -3522148667591954432,  6212339063633101824])