# Tensorflow Fundamentals

- Intro to Tensors
- Getting info from tensors
- Manipulating Tesors
- Tensors & NumPy
- Using @tf.function (a way to speed up your regula Python functions)
- Using GPus with TensorFlow (or TPUs)
- Different Exercises

In [2]:
import tensorflow as tf
print(tf.__version__)

2.20.0


In [3]:
# Create tensors with tf.constant()
# There are different way to create tensors
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of demensions (ndim)
scalar.ndim

0

In [5]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# Check the dimension of our vector
vector.ndim

1

In [7]:
# Check matrix tesors
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
# Matrix float data type
matrix_float = tf.constant([[10.,7.],[7.,10.]],dtype=tf.float16)
matrix_float

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.]], dtype=float16)>

In [10]:
matrix_float.ndim

2

In [11]:
# Tesor
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

- What is a Tesor? n-dimentional, 1d vector, 2d matrix, 3d and more tensor
- What is difference between tf.constant and tf.variable
- when in doubt, use tf.constant and change it later if needed, how

In [13]:
# tensor variables
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# changeable_tensor[0] = 11
# changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [15]:
changeable_tensor[0].assign(8)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([8, 7], dtype=int32)>

In [18]:
# unchangeable_tensor[0].assign(8)
# unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [19]:
# random tesnsors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

- Why might we need random tensors?

In [21]:
# Shuffleing Tensors
not_shuffled = tf.constant([[10,7],[3,4],[2,5]])

tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

- Why do we need to shuffle?

In [22]:
# Other way to make tesors
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

- The main difference btewen NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing)

In [23]:
# NumPy array to tensor

import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

A = tf.constant(numpy_A, shape=(2, 3, 4))
A


<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

## Getting information from tensors

- Shape
- Rank
- Axis or dimension
- Size

Create a table with there meaning and code

In [24]:
# create a 3D tensor
rank_4_tensor = tf.ones(shape=[2,3,4,5])
rank_4_tensor


<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [26]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [28]:
# Get various attribute of our tensors
print('Datatype of every element:', rank_4_tensor.dtype)
print('Number of dimensions (rank):', rank_4_tensor.ndim)
print('Shape of tensor:', rank_4_tensor.shape)
print('Elements along the 0 axis:', rank_4_tensor.shape[0])
print('Elements along the last axis:', rank_4_tensor.shape[-1])
print('Total number of elements in our tensor:', tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: 120


Tensors can be indexded just like python lists

In [33]:
# Get the first 2 elments of each dimentions
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [35]:
rank_2t = tf.zeros([2, 2])
rank_2t

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [36]:
### Adding an extra dimension to our rank 2 tensor
# tf.newaxis
rank_3t = rank_2t[..., tf.newaxis]
rank_3t

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[0.],
        [0.]],

       [[0.],
        [0.]]], dtype=float32)>

In [41]:
tf.expand_dims(rank_2t, axis=-1
               )

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[0.],
        [0.]],

       [[0.],
        [0.]]], dtype=float32)>

## Tensor Operations (Manipulating Tensor)

### Basic Operations (+, -, *, /)

In [44]:
tensor = tf.constant([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [45]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [46]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [47]:
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [50]:
## To speed up this using GPU use tf.math operators
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

Add a table of other available math operators in tensroflow

### Matrix Multiplication

- The inner dimensions must match
- The resulting matrix has the shape of the outer dimensions

In [61]:
t1 = tf.constant([[1,2,5],[7,2,1],[3,3,3]])
t2 = tf.constant([[3,5],[6,7],[1,8]])

# create 3D tensors t3 of shape (2, 3, 4), t4 of shape (4, 3, 2)
t3 = tf.random.normal(shape=(8, 3, 4))
t4 = tf.random.normal(shape=(8, 4, 2))

tf.linalg.matmul(t1, t2)  # you can drop .linalg
t3.shape, t4.shape
tf.matmul(t3, t4)

<tf.Tensor: shape=(8, 3, 2), dtype=float32, numpy=
array([[[-2.7961907 , -0.5451489 ],
        [ 2.716382  ,  0.42042208],
        [ 3.0365324 ,  2.1323786 ]],

       [[-1.4773636 , -0.95461816],
        [ 2.9245973 ,  0.0611341 ],
        [ 0.479088  ,  1.8230513 ]],

       [[ 2.3724813 ,  1.4900798 ],
        [-3.6119812 , -0.48284194],
        [-2.0441806 , -0.24731134]],

       [[ 0.835039  ,  0.02144725],
        [ 2.1637087 ,  0.1938662 ],
        [-1.2490331 , -0.49296123]],

       [[-1.1697216 ,  1.262163  ],
        [ 0.9769732 , -2.8025804 ],
        [ 0.5752451 ,  2.423177  ]],

       [[ 1.5218774 ,  3.2715662 ],
        [ 0.8609528 ,  5.4109836 ],
        [-1.296712  , -2.1460524 ]],

       [[-0.5012382 ,  0.9560974 ],
        [ 1.2099814 , -0.31279096],
        [-0.05813205, -1.5208657 ]],

       [[-0.2545185 , -0.27342048],
        [-0.03575784,  0.38313597],
        [ 3.520224  , -1.7626754 ]]], dtype=float32)>

In [62]:
# Two same shaped metrices
X = tf.constant([[1,2],[3,4],[5,6]])
Y = tf.constant([[7,8],[9,10],[11,12]])
X, Y

# Reshaping y


# Then multiplying


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

ML and DL use case add projects there?