# Tensorflow Fundamentals

- Intro to Tensors
- Getting info from tensors
- Manipulating Tesors
- Tensors & NumPy
- Using @tf.function (a way to speed up your regula Python functions)
- Using GPus with TensorFlow (or TPUs)
- Different Exercises

In [1]:
import tensorflow as tf
print(tf.__version__)

2.20.0


In [2]:
# Create tensors with tf.constant()
# There are different way to create tensors
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of demensions (ndim)
scalar.ndim

0

In [4]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check the dimension of our vector
vector.ndim

1

In [6]:
# Check matrix tesors
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# Matrix float data type
matrix_float = tf.constant([[10.,7.],[7.,10.]],dtype=tf.float16)
matrix_float

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.]], dtype=float16)>

In [9]:
matrix_float.ndim

2

In [10]:
# Tesor
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

- What is a Tesor? n-dimentional, 1d vector, 2d matrix, 3d and more tensor
- What is difference between tf.constant and tf.variable
- when in doubt, use tf.constant and change it later if needed, how

In [12]:
# tensor variables
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# changeable_tensor[0] = 11
# changeable_tensor

In [14]:
changeable_tensor[0].assign(8)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([8, 7], dtype=int32)>

In [15]:
# unchangeable_tensor[0].assign(8)
# unchangeable_tensor

In [16]:
# random tesnsors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

- Why might we need random tensors?

In [17]:
# Shuffleing Tensors
not_shuffled = tf.constant([[10,7],[3,4],[2,5]])

tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

- Why do we need to shuffle?

In [18]:
# Other way to make tesors
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

- The main difference btewen NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing)

In [19]:
# NumPy array to tensor

import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

A = tf.constant(numpy_A, shape=(2, 3, 4))
A


<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

## Getting information from tensors

- Shape
- Rank
- Axis or dimension
- Size

Create a table with there meaning and code

In [20]:
# create a 3D tensor
rank_4_tensor = tf.ones(shape=[2,3,4,5])
rank_4_tensor


<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [21]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [22]:
# Get various attribute of our tensors
print('Datatype of every element:', rank_4_tensor.dtype)
print('Number of dimensions (rank):', rank_4_tensor.ndim)
print('Shape of tensor:', rank_4_tensor.shape)
print('Elements along the 0 axis:', rank_4_tensor.shape[0])
print('Elements along the last axis:', rank_4_tensor.shape[-1])
print('Total number of elements in our tensor:', tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: 120


Tensors can be indexded just like python lists

In [23]:
# Get the first 2 elments of each dimentions
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[1.],
         [1.],
         [1.],
         [1.]]]], dtype=float32)>

In [24]:
rank_2t = tf.zeros([2, 2])
rank_2t

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [25]:
### Adding an extra dimension to our rank 2 tensor
# tf.newaxis
rank_3t = rank_2t[..., tf.newaxis]
rank_3t

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[0.],
        [0.]],

       [[0.],
        [0.]]], dtype=float32)>

In [26]:
tf.expand_dims(rank_2t, axis=-1
               )

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[0.],
        [0.]],

       [[0.],
        [0.]]], dtype=float32)>

## Tensor Operations (Manipulating Tensor)

### Basic Operations (+, -, *, /)

In [27]:
tensor = tf.constant([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [28]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [29]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [30]:
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [31]:
## To speed up this using GPU use tf.math operators
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

Add a table of other available math operators in tensroflow

### Matrix Multiplication

- The inner dimensions must match
- The resulting matrix has the shape of the outer dimensions

In [32]:
t1 = tf.constant([[1,2,5],[7,2,1],[3,3,3]])
t2 = tf.constant([[3,5],[6,7],[1,8]])

# create 3D tensors t3 of shape (2, 3, 4), t4 of shape (4, 3, 2)
t3 = tf.random.normal(shape=(8, 3, 4))
t4 = tf.random.normal(shape=(8, 4, 2))

tf.linalg.matmul(t1, t2)  # you can drop .linalg
t3.shape, t4.shape
tf.matmul(t3, t4)

<tf.Tensor: shape=(8, 3, 2), dtype=float32, numpy=
array([[[ 2.4069939 , -0.04422545],
        [-2.4938686 , -0.32229608],
        [-3.5064552 ,  1.0692767 ]],

       [[-0.1909743 ,  3.1171238 ],
        [ 0.38967383,  2.2547488 ],
        [ 0.99709684, -1.559989  ]],

       [[ 0.09320642, -0.73237425],
        [ 1.3203852 , -1.6369658 ],
        [ 0.90508264, -0.90458345]],

       [[10.737851  ,  1.1992137 ],
        [ 0.9134586 ,  0.97173136],
        [-0.77092266, -1.8435224 ]],

       [[-0.09757845,  0.17238651],
        [-0.07892454,  0.31379732],
        [-2.5599124 ,  1.8939059 ]],

       [[-2.2484756 ,  1.9789513 ],
        [ 1.5144639 , -1.0594988 ],
        [-3.1033123 ,  3.5184028 ]],

       [[-1.5095519 , -0.03195433],
        [-4.6596713 , -0.54824245],
        [-0.48668933,  0.90518546]],

       [[ 3.6174378 , -0.1857531 ],
        [ 1.9894493 , -3.5202394 ],
        [ 1.9850233 ,  1.6158969 ]]], dtype=float32)>

In [33]:
# Two same shaped metrices
X = tf.constant([[1,2],[3,4],[5,6]])
Y = tf.constant([[7,8],[9,10],[11,12]])
print(X.shape, Y.shape)

# Reshaping y
tf.reshape(Y, shape=(2,3))

# Then multiplying
print(tf.matmul(X, tf.reshape(Y, shape=(2,3))))
print(tf.matmul(tf.reshape(X, shape=(2,3)), Y))


(3, 2) (3, 2)
tf.Tensor(
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)


In [34]:
## We can achieve the same using tf.transpose

print(tf.matmul(tf.transpose(X), Y))

tf.Tensor(
[[ 89  98]
 [116 128]], shape=(2, 2), dtype=int32)


### The dot product
Matrix multiplication is also referred to as the dot product

this can be peformed using matrix multiplications using

- tf.matmul()
- tf.tensordot() - what is tensort dot does

generally when performing matrix multiplication on two tesors and one of the axes doesn't line up we will transpose rather than reshape to get satify dot product conditions

In [35]:
# Usage of tensordot
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

### Chaning the datatype of a tensor tf.cast()

In [36]:
tf.__version__

'2.20.0'

In [37]:
# create a new tensor
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [38]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [39]:
D = tf.cast(B, dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

### Aggregating tensors
- Get the min
- max
- mean
- sum
-

In [40]:
C = tf.constant([-1, -5])

In [41]:
D = tf.constant([-5, 10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-5, 10], dtype=int32)>

In [42]:
tf.minimum(D, C)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-5, -5], dtype=int32)>

In [43]:
tf.maximum(D, C)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-1, 10], dtype=int32)>

In [44]:
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([32, 16, 24, 83, 55, 76,  2, 52, 73, 47, 38, 66,  1, 23, 14, 49, 40,
       14, 78, 83, 43, 78, 11, 36, 98, 43, 20, 40, 63, 32, 39, 87, 78, 58,
       21, 87, 22,  8,  2, 75, 37, 51, 27, 60, 10, 55, 16, 81, 48, 30])>

In [45]:
tf.abs(E)

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([32, 16, 24, 83, 55, 76,  2, 52, 73, 47, 38, 66,  1, 23, 14, 49, 40,
       14, 78, 83, 43, 78, 11, 36, 98, 43, 20, 40, 63, 32, 39, 87, 78, 58,
       21, 87, 22,  8,  2, 75, 37, 51, 27, 60, 10, 55, 16, 81, 48, 30])>

In [46]:
# Getting the minimum of a tensor
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [47]:
# mean of a tensor
tf.reduce_mean(tf.cast(E, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=44.4375>

In [48]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2222>

### tensorflow Probablity

In [49]:
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=694>

In [50]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=694.1663818359375>

In [51]:
tfp.stats.stddev(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=26.34703826904297>

In [52]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=26.34703826904297>

### Positional Maximum and minimum

In [53]:
tf.random.set_seed(42)

F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [54]:
F[tf.math.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [58]:
F[tf.math.argmin(F)], F[tf.argmax(F)]

(<tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>)

## Tensor Squizing (removing all single dimensions)


In [60]:
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 1, 50))

G

<tf.Tensor: shape=(1, 1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[[0.7413678 , 0.62854624, 0.01738465, 0.3431449 ,
            0.51063764, 0.3777541 , 0.07321596, 0.02137029,
            0.2871771 , 0.4710616 , 0.6936141 , 0.07321334,
            0.93251204, 0.20843053, 0.70105827, 0.45856392,
            0.8596262 , 0.92934334, 0.20291913, 0.76865506,
            0.60016024, 0.27039742, 0.88180614, 0.05365038,
            0.42274463, 0.89037776, 0.7887033 , 0.10165584,
            0.19408834, 0.27896714, 0.39512634, 0.12235212,
            0.38412368, 0.9455296 , 0.77594674, 0.94442344,
            0.04296565, 0.4746096 , 0.6548251 , 0.5657116 ,
            0.13858628, 0.3004663 , 0.3311677 , 0.12907016,
            0.6435652 , 0.45473957, 0.68881893, 0.30203617,
            0.49152803, 0.26529062]]]]]], dtype=float32)>

In [61]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.7413678 , 0.62854624, 0.01738465, 0.3431449 , 0.51063764,
        0.3777541 , 0.07321596, 0.02137029, 0.2871771 , 0.4710616 ,
        0.6936141 , 0.07321334, 0.93251204, 0.20843053, 0.70105827,
        0.45856392, 0.8596262 , 0.92934334, 0.20291913, 0.76865506,
        0.60016024, 0.27039742, 0.88180614, 0.05365038, 0.42274463,
        0.89037776, 0.7887033 , 0.10165584, 0.19408834, 0.27896714,
        0.39512634, 0.12235212, 0.38412368, 0.9455296 , 0.77594674,
        0.94442344, 0.04296565, 0.4746096 , 0.6548251 , 0.5657116 ,
        0.13858628, 0.3004663 , 0.3311677 , 0.12907016, 0.6435652 ,
        0.45473957, 0.68881893, 0.30203617, 0.49152803, 0.26529062],
       dtype=float32)>,
 TensorShape([50]))

## One-hot Encoding


In [64]:
# Create a list of indices
some_list = [0, 1, 1, 2, 2, 0, 3]

# one hot encolde
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(7, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [67]:
# specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="x", off_value="-1")

<tf.Tensor: shape=(7, 4), dtype=string, numpy=
array([[b'x', b'-1', b'-1', b'-1'],
       [b'-1', b'x', b'-1', b'-1'],
       [b'-1', b'x', b'-1', b'-1'],
       [b'-1', b'-1', b'x', b'-1'],
       [b'-1', b'-1', b'x', b'-1'],
       [b'x', b'-1', b'-1', b'-1'],
       [b'-1', b'-1', b'-1', b'x']], dtype=object)>

## Basic Math Operations

In [68]:
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [69]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [70]:
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [71]:
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensors and NumPy

In [73]:
import numpy as np

J = tf.constant(np.array([3., 2., 19.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  2., 19.])>

In [75]:
np.array(J), type(np.array(J))

(array([ 3.,  2., 19.]), numpy.ndarray)

In [77]:
J.numpy(), type(J.numpy())

(array([ 3.,  2., 19.]), numpy.ndarray)

In [79]:
# The distinction between Numpy and tesnor created data type
Numpy_J = tf.constant (np.array([3., 5., 6.]))
tensor_J = tf.constant([3., 5., 6.])

Numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

# Neural Networks with Regression

- Input layer shape
- Hidden layer(s)
- Neurons per hidden..layer
- Output layer shape
- Hidden activation
- output activation
- loss function
- optimizer