# Tensorflow Fundamentals

- Intro to Tensors
- Getting info from tensors
- Manipulating Tesors
- Tensors & NumPy
- Using @tf.function (a way to speed up your regula Python functions)
- Using GPus with TensorFlow (or TPUs)
- Different Exercises

In [1]:
import tensorflow as tf
print(tf.__version__)

2.20.0


In [2]:
# Create tensors with tf.constant()
# There are different way to create tensors
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of demensions (ndim)
scalar.ndim

0

In [4]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check the dimension of our vector
vector.ndim

1

In [7]:
# Check matrix tesors
matrix = tf.constant([[10,7],[7,10]])
matrix

2

In [8]:
matrix.ndim

2

In [9]:
# Matrix float data type
matrix_float = tf.constant([[10.,7.],[7.,10.]],dtype=tf.float16)
matrix_float

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.]], dtype=float16)>

In [10]:
matrix_float.ndim

2

In [11]:
# Tesor
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

- What is a Tesor? n-dimentional, 1d vector, 2d matrix, 3d and more tensor
- What is difference between tf.constant and tf.variable
- when in doubt, use tf.constant and change it later if needed, how

In [18]:
# tensor variables
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [19]:
changeable_tensor[0] = 11
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [20]:
changeable_tensor[0].assign(8)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([8, 7], dtype=int32)>

In [21]:
unchangeable_tensor[0].assign(8)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [24]:
# random tesnsors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

ML and DL use case add projects there?